### PR TITLE
Fix path to s3cmd

### PR DESCRIPTION
**Pull request by symroe**

### CODE REVIEW

**Comment by chris48s** [comment]
doh - missed a spot in https://github.com/DemocracyClub/who_deploy/commit/b24913117b6bc56bdb1d16a4d16e59c21c23eea8

Just to anticipate the next issue you're going to hit, you'll also want to copy the (empty) s3 config file to the home dir of whatever user this job runs under (presumably `wcivf` in this case), something like:

```
  - name: Install .s3cfg file
    template:
      src: "files/conf/s3cfg"
      dest: "/home/wcivf/.s3cfg"
      group: wcivf
      owner: wcivf
      mode: 0755
```

s3cmd > 2.0 requires a config file even if using role-based auth. I installed it in the build for root because the `@reboot` jobs runs as root, but I missed this

**Comment by symroe** [comment]
Got a bit confused about this. It's working on an instance for the `wcivf` user without a config file, and [reading the code](https://github.com/s3tools/s3cmd/blob/master/S3/Config.py#L245) it looks like the config file isn't required.

Can you expand on why it's needed?

**Comment by chris48s** [comment]
What version of s3cmd is running on that instance and what version of python is it running under?

Bear in mind the code on `master` in https://github.com/s3tools/s3cmd contains a fix for https://github.com/s3tools/s3cmd/issues/930 but that hasn't been packaged as 2.0.3 yet.

**Comment by symroe** [comment]
```
sudo su wcivf

s3cmd --version
s3cmd version 2.0.2

python --version
Python 3.6.7
```

**Comment by symroe** [comment]
Oh of course `s3cmd` is using `/usr/bin/python` and that's `2.7.15rc1`

**Comment by chris48s** [comment]
Running under python 2 allows it to use role-based auth if `access_key` and `secret_key` are blank, but I think s3cmd >= 2.0 still requires us to specify that in a config file. I guess either

* I am wrong about that, or
* the `wcivf` user is able to pick up the config file that [already exists](https://github.com/DemocracyClub/who_deploy/commit/b24913117b6bc56bdb1d16a4d16e59c21c23eea8) in `/root/.s3cfg`

**Comment by symroe** [comment]
This seems to work as is, so I'm going to merge and will add the empty file if I need to

**Comment by chris48s** [comment]
I may have got confused - its possible the s3cmd 2.0.2/python 2 combo doesn't need a blank config file. I'll test what happens if I remove it next time I'm doing work on deploy scripts. If so, that's a bit of cruft we can remove..

**Pull request merged**
