### PR TITLE
Update ubuntu_ami_id to ami-ff46a298

### PR DESCRIPTION
**Pull request by polling-bot-4000**
Found new Ubuntu 16.04 LTS (hvm:ebs-ssd) image in eu-west-2: `ami-ff46a298` :penguin:

### CODE REVIEW

**Comment by symroe** [comment]
Hi @polling-bot-4000! Is there any way of getting a changelog or what is new in the image?

**Comment by chris48s** [comment]
Answers on a postcard!

One of the reasons I decided to make a script to check this is because the release schedule is so unpredictable. Sometimes there are weeks between images. Sometimes they release new images a few days apart. My guess is that they correspond to some combination of important security patches, kernel updates or updates to the [cloud-init package](https://help.ubuntu.com/community/CloudInit).

In terms of checking for compatibility, I'm probably not going to study the release notes for the linux kernel. I just want to make sure when we build, we are starting from the latest cloud image.

Are you interested more from the perspective of knowing if a new image is out, does this mean we should re-build and deploy?

**Comment by symroe** [comment]
Yeah, maybe it's ok. Just feels a bit odd that we really consider updates to, for example, a python package, but don't for the entire OS under it. I guess that's because APIs are a lot more stable in general etc. 

Would be nice to know if it's a critical update, but the news normally lets us know about really big things.

**Comment by chris48s** [comment]
Whether the mechanism is

* `unattended-upgrades`/`aptcron`
* updating the base image we build from or
* logging in and running:

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```

by hand

the only level I really think about this on is:

up-to-date operating system = good
out-of-date operating system = bad

**Pull request merged**
